The code problems sets in this excercise sheet are taken from many helpful resources. 

Check them out for further practice:

https://www.kaggle.com/utsav15/100-numpy-exercises

https://www.w3resource.com/python-exercises/numpy/index.php
        
https://www.machinelearningplus.com/python/101-numpy-exercises-python/
    
https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/ ( *Multiple solutions per problem* )
    
https://favtutor.com/blogs/numpy-exercises-python

Level your coding skills by solving challenges: https://www.hackerrank.com/domains/python/numpy/difficulty/all/page/1

In [3]:
from numpy import *

### Question: Create a null vector of size 10

### Answer:

In [3]:
nullVector = zeros(10)
print("null vector :",nullVector)

null vector : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### Question: Create a vector with values ranging from 10 to 49


In [9]:
vector1 = arange(10 , 50)
print(vector1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### Question: Reverse a vector (first element becomes last)

### Answer:

In [26]:
vect1 = arange (1 , 11)
reverse_vect1 = vect1 [::-1]
print(vect1)
print(reverse_vect1)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


### Question: Create a 3x3 matrix with values ranging from 0 to 8

### Answer:

In [32]:
matrix = arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Question: Find indices of non-zero elements from [1,2,0,0,4,0]

### Answer:

In [33]:
arr = array([1,2,0,0,4,0])
indices = nonzero(arr)
print(indices)

(array([0, 1, 4]),)


### Question: Create a 10x10 array with random values and find the minimum, maximum and mean values

### Answer:

In [36]:
arr = random.rand(10,10)
minVal = arr.min()
maxVal = arr.max()
meanVal = arr.mean()

print("Array :",arr)
print("Minimum value :",minVal)
print("Maximum value :",maxVal)
print("Mean value :",meanVal)

Array : [[0.91197918 0.51157622 0.38550597 0.99660365 0.25886249 0.50722541
  0.33163359 0.73786316 0.00657149 0.10758196]
 [0.52133827 0.37369815 0.53312004 0.9008694  0.77081074 0.3157012
  0.41115634 0.24182007 0.09348468 0.12624168]
 [0.07621954 0.11194959 0.51776122 0.7507779  0.38103489 0.08384076
  0.70607616 0.01267267 0.59155928 0.35902774]
 [0.42639494 0.92729405 0.51119039 0.43500305 0.1319147  0.60012334
  0.51960427 0.3930822  0.21589883 0.72865181]
 [0.57735388 0.67892405 0.06383185 0.87670174 0.23325474 0.99968281
  0.00634888 0.59226758 0.67327887 0.39181038]
 [0.79734698 0.8538949  0.35798927 0.45684856 0.14785659 0.38600234
  0.57616    0.17146073 0.44007064 0.46046338]
 [0.40103436 0.93119667 0.63559783 0.98561134 0.2034902  0.69713216
  0.97066336 0.13315012 0.70726708 0.10540426]
 [0.09929773 0.55908257 0.43228909 0.84401375 0.02914241 0.65071328
  0.78262227 0.49341196 0.48253151 0.61002423]
 [0.39617703 0.47478047 0.579721   0.38524678 0.21611107 0.09822488
  0.3

### Question: What is the result of the following expressions?
print(0 * np.nan)

print(np.nan == np.nan)

print(np.inf > np.nan)

print(np.nan - np.nan)

print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)

### Answer

In [ ]:
#nan
#False
#False
#nan
#True
#False

In [48]:
print(0 * nan)

print(nan == nan)

print(inf > nan)

print(nan - nan)

print(nan in set([nan]))

print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


### Question: Write a NumPy program to convert a list and tuple into arrays. 
List to array:  [1 2 3 4 5 6 7 8]
    
Tuples to array:  ((8, 4), (6,1), (2, 3))
    
## Answer:

In [ ]:
my_list =[1,2,3,4,5,6,7,8]
tuble = (8,4,6,1,2,3)
list_to_arr = array(my_list)
tuple_to_arr = array(tuble).reshape(3,2)

print(list_to_arr)
print(tuple_to_arr)

[1 2 3 4 5 6 7 8]
[[8 4]
 [6 1]
 [2 3]]


### Question: Write a NumPy program to append values to the end of an array.
Original array:  [10, 20, 30]
After append values to the end of the array:  [10 20 30 40 50 60 70 80 90]

### Answer:

In [68]:
arr3 = array([10, 20, 30])
arr4 = array([40,50,60,70,80,90])
new_arr = hstack((arr3,arr4))
print("new array :",new_arr)

new array : [10 20 30 40 50 60 70 80 90]


### Question: How to add a border (filled with 0's) around an existing array? 

### Answer:

In [71]:
arr = array([[1,2,1],[3,4,3],[5,6,5]])
padded = pad(arr,pad_width=1)
print(padded)

[[0 0 0 0 0]
 [0 1 2 1 0]
 [0 3 4 3 0]
 [0 5 6 5 0]
 [0 0 0 0 0]]


### Question: Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

### Answer:

In [ ]:
element =99
shape = (6,7,8)
coordent = unravel_index(element,shape)

# for integr result
#coordent = tuple(int(x) for x in coordent) 


print(coordent)

(np.int64(1), np.int64(5), np.int64(3))


### Question: Normalize a 5x5 random matrix

### Answer:

In [8]:
mat = random.rand(5,5)*100

normalize_mat = (mat-mat.min()) / (mat.max()-mat.min())

print("original matrix :\n", mat)
print("normalized matrix :\n", normalize_mat)

original matrix :
 [[34.00398176 15.91597549 98.43098002 23.71670427  3.04022768]
 [ 9.20027963 99.4671376  30.60622115 22.719234   56.07720994]
 [46.62771392 27.95204929 79.27520857 64.0216158  72.37460533]
 [40.04253378 56.18334203 31.17631107 29.07191939  5.20346187]
 [70.07021367 33.54377277 74.7138662  86.23847101 90.07826058]]
normalized matrix :
 [[0.32111113 0.13352857 0.98925448 0.21442641 0.        ]
 [0.06388312 1.         0.28587449 0.2040821  0.55002263]
 [0.45202616 0.25834927 0.79059861 0.63241048 0.71903556]
 [0.38373423 0.55112327 0.29178663 0.26996294 0.02243393]
 [0.69513776 0.31633851 0.74329498 0.86281146 0.90263219]]


### Question: Given a 1D array, negate all elements which are between 3 and 8, in place

### Answer:

In [14]:
arr = array([1,2,3,4,5,6,7,8])
condition = (arr>3) & (arr<8)
arr[condition] *= (-1)


print("array with negated :\n",arr)

array with negated :
 [ 1  2  3 -4 -5 -6 -7  8]


### Question: How to find common values between two arrays? 

### Answer:

In [18]:
arr1 = array ([1,4,2,9,5,66,934,22,0,7123])
arr2 = array ([1,5,66,9,934,999,7123,0,545])

common = intersect1d(arr1,arr2)

print("common values between arr1 & arr2 :\n",common)

common values between arr1 & arr2 :
 [   0    1    5    9   66  934 7123]


### Question: Write a NumPy program to test whether each element of a 1-D array is also present in a second array. 
Array1: [ 0 10 20 40 60]

Array2: [0, 40]

Expected Output:[ True False False True False]

### Answer:

In [21]:
arr1 = array([0,10,20,40,60])
arr2 = array([0,40])

result = in1d(arr1 , arr2 )
print(result)

[ True False False  True False]


C:\Users\B UNIT\AppData\Local\Temp\ipykernel_1208\1181421639.py:4: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  result = in1d(arr1 , arr2 )


### Question: How to get all the dates corresponding to the month of July 2016?

### Answer:

In [22]:
dates = arange (datetime64('2016-07-01'),datetime64('2016-08-01'),dtype='datetime64[D]')
print("corresponding dates",dates)

corresponding dates ['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### Question: Extract the integer part of a random array using 5 different methods

### Answer:

In [28]:
arr = random.uniform(0,10,5)

method1 = floor(arr)
method2 = trunc(arr)
method3 = fix(arr)
method4 = arr.astype(int)
method5 =  modf(arr)

print("original array :\n",arr)
print("Method 1 :\n",method1)
print("Method 2 :\n",method2)
print("Method 3 :\n",method3)
print("Method 4 :\n",method4)
print("Method 5 :\n",method5)

original array :
 [6.27648438 7.71263395 1.34715808 1.66372001 3.74633293]
Method 1 :
 [6. 7. 1. 1. 3.]
Method 2 :
 [6. 7. 1. 1. 3.]
Method 3 :
 [6. 7. 1. 1. 3.]
Method 4 :
 [6 7 1 1 3]
Method 5 :
 (array([0.27648438, 0.71263395, 0.34715808, 0.66372001, 0.74633293]), array([6., 7., 1., 1., 3.]))


### Question: Consider two random array A and B, check if they are equal 

### Answer:

In [34]:
arr1 = random.randint(0,5,(3,3))
arr2 = random.randint(0,5,(3,3))
is_equal = array_equal(arr1,arr2)

print("first array :\n",arr1)
print("second array :\n",arr2)
print("Are Equal? :\n",is_equal)


first array :
 [[1 3 3]
 [4 2 3]
 [1 1 4]]
second array :
 [[0 2 1]
 [1 4 2]
 [0 2 0]]
Are Equal? :
 False


### Question: How to find the closest value (to a given scalar) in a vector?

### Answer:

In [36]:
vect = array([1, 5, 9, 12, 20])
scalar = 10
closest_value = vect[abs(vect-scalar).argmin()]

print("closest value :", closest_value)


closest value : 9


### Question: Find the nearest value from a given value in an array

### Answer:

In [39]:
arr = array([1,2,500,13,680])
value = 601
near = arr[abs(arr-value).argmin()]

print("the nearest value :\n",near)

the nearest value :
 680


### Question: Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

### Answer:

In [42]:
arr=array([1,2,66,4,9,11,4356,38])
values = arr[arr > 10]
indices = where(arr > 10)[0]
print("indices:\n",indices)

indices:
 [2 5 6 7]


### Question: Write a NumPy program to save a NumPy array to a text file.

### Answer:

In [4]:
arr = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
savetxt("array_data.txt", arr, fmt="%d")
print("Array saved to 'array_data.txt'")

Array saved to 'array_data.txt'


### Question: How to read the following file?

### Answer:

In [5]:
arr = loadtxt("array_data.txt", dtype=int)

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Question: What is the equivalent of enumerate for numpy arrays?

### Answer:

In [6]:
arr = array([[10, 20, 30], [40, 50, 60]])

for index, value in ndenumerate(arr):
    print(index, value)

(0, 0) 10
(0, 1) 20
(0, 2) 30
(1, 0) 40
(1, 1) 50
(1, 2) 60


### Question: Subtract the mean of each row of a matrix

### Answer:

In [7]:
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

result = A - A.mean(axis=1, keepdims=True)

print(result)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


### Question: How to sort an array by the nth column? 

### Answer:

In [8]:
arr = array([[3, 2, 5],
             [1, 4, 2],
             [7, 0, 9]])

n = 1 

sorted_arr = arr[arr[:, n].argsort()]

print(sorted_arr)

[[7 0 9]
 [3 2 5]
 [1 4 2]]


### Question: Write a NumPy program to sort pairs of first name and last name return their indices. (first by last name, then by first name).
first_names = (‘Betsey’, ‘Shelley’, ‘Lanell’, ‘Genesis’, ‘Margery’)

last_names = (‘Battle’, ‘Brien’, ‘Plotner’, ‘Stahl’, ‘Woolum’)

### Answer:

In [9]:
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')

indices = lexsort((first_names, last_names))

print(indices)

[0 1 2 3 4]


### Question: How to tell if a given 2D array has null columns?

### Answer:

In [10]:
arr = array([[1, nan, 3],
             [4, nan, 6],
             [7, nan, 9]])

# Check which columns are entirely NaN
null_columns = all(isnan(arr), axis=0)

print(null_columns)

[False  True False]


### Question: Considering a four dimensions array, how to get sum over the last two axis at once? 
happens in avgpooling [batch,channel,hight,width]

### Answer:

In [11]:
arr = random.rand(2, 3, 4, 5)  

sum_last_two = arr.sum(axis=(2, 3))

print(sum_last_two)
print(sum_last_two.shape)

[[ 8.95188735 10.70036151 10.93420909]
 [ 8.64061868  9.99413161 10.15650665]]
(2, 3)


### Related: Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 
happens in avgpooling [batch,channel,hight,width]

### Answer:

In [12]:
arr = arange(16*16).reshape(16, 16)

# Reshape into 4x4 blocks: (4,4,4,4)
blocks = arr.reshape(4, 4, 4, 4)

# Sum over the last two axes (each 4x4 block)
block_sums = blocks.sum(axis=(2, 3))

print(block_sums)
print(block_sums.shape)

[[ 120  376  632  888]
 [1144 1400 1656 1912]
 [2168 2424 2680 2936]
 [3192 3448 3704 3960]]
(4, 4)


### Question: How to swap two rows of an array? 

### Answer:

In [13]:
arr = array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

# Swap row 0 and row 2
arr[[0, 2]] = arr[[2, 0]]

print(arr)

[[7 8 9]
 [4 5 6]
 [1 2 3]]


### Question: How to get the n largest values of an array
happens in one-to-many classifier (top n predictions)

### Answer:

In [14]:
arr = array([10, 50, 20, 40, 30])

n = 3  # number of top values

# Get indices of n largest values
top_indices = arr.argsort()[-n:][::-1]

# Get the top n values
top_values = arr[top_indices]

print("Indices of top n:", top_indices)
print("Top n values:", top_values)

Indices of top n: [1 3 4]
Top n values: [50 40 30]


### Question: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
simulating sequential model training feed

### Answer:

In [15]:

Z = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Create sliding windows of size 4
R = lib.stride_tricks.sliding_window_view(Z, window_shape=4)

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
